### ISSUE TITLE
GUIManager privateの表記ミス

### ISSUE THREAD

**Issue by KataokaNagi** [Kdai58/kodo2a#20]

**Comment by KataokaNagi** [comment]
privateって、変数やメソッドの前にハイフン2つじゃないかな？
間違ってたらごめん
https://qiita.com/Usek/items/a206b8e49c02f756d636

**Comment by Kdai58** [comment]
俺も最初そう思ったんだけど，PEP8だと”先頭にアンダースコア1個”になってるらしい．
https://qiita.com/shiracamus/items/bc3bdfc206b39e0a75b2

**Comment by KataokaNagi** [comment]
ほんまや！

勉強になったありがとう～
Qiitaは下手に信用しない方がいいね
